apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: aa-prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      service: aa
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
